# This file was generated by GoReleaser. DO NOT EDIT.
cask "clipctl" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "6e5dc36f15d580f88445795cac43a4bb276858823d021df7cdc133824b67b29b"
      url "https://github.com/nicks/clipctl/releases/download/v#{version}/clipctl_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/nicks/clipctl/"
    end
    on_arm do
      sha256 "a577ff1bbf10ee5e50bf5fd9dbc2fb103bb5114a5adf85a99d6ff64f930e26d9"
      url "https://github.com/nicks/clipctl/releases/download/v#{version}/clipctl_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/nicks/clipctl/"
    end
  end

  name "clipctl"
  desc "Cross-platform clipboard debugger"
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clipctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clipctl"]
    end
  end

  # No zap stanza required

end
