# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rift < Formula
  desc "Tiling window manager for macOS (nicks fork of acsandmann/rift)"
  homepage "https://github.com/nicks/rift"
  version "0.5.5-nicks.3"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/nicks/rift/releases/download/v0.5.5-nicks.3/rift_0.5.5-nicks.3_darwin_amd64.tar.gz"
    sha256 "93710d73c166342d2f0d19bbff0d9ac06a72e6bbdb980611ab0c0eea10a0e270"

    define_method(:install) do
      bin.install "rift"
      bin.install "rift-cli"
      pkgshare.install "rift.default.toml"

      # Ad-hoc sign: rift talks to private SkyLight APIs and macOS is unhappy
      # about an unsigned binary holding Accessibility permissions.
      system "codesign", "--force", "-s", "-", "#{bin}/rift"
      system "codesign", "--force", "-s", "-", "#{bin}/rift-cli"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/nicks/rift/releases/download/v0.5.5-nicks.3/rift_0.5.5-nicks.3_darwin_arm64.tar.gz"
    sha256 "635cefb94e2f9741a4146a2f1b6e2b802d2c8e73e54b12371f85291c5279a89f"

    define_method(:install) do
      bin.install "rift"
      bin.install "rift-cli"
      pkgshare.install "rift.default.toml"

      # Ad-hoc sign: rift talks to private SkyLight APIs and macOS is unhappy
      # about an unsigned binary holding Accessibility permissions.
      system "codesign", "--force", "-s", "-", "#{bin}/rift"
      system "codesign", "--force", "-s", "-", "#{bin}/rift-cli"
    end
  end

  conflicts_with "acsandmann/tap/rift"

  def caveats
    <<~EOS
      rift requires Accessibility permissions to control windows.
      Grant them in System Settings > Privacy & Security > Accessibility.

      To install the example configuration:
        mkdir -p ~/.config/rift
        cp #{HOMEBREW_PREFIX}/share/rift/rift.default.toml ~/.config/rift/config.toml

      To run rift in the background:
        brew services start nicks/tap/rift
    EOS
  end

  service do
    run [opt_bin/"rift"]
    keep_alive true
    process_type :interactive
    environment_variables PATH: std_service_path_env, LANG: "en_US.UTF-8"
    log_path var/"log/rift.log"
    error_log_path var/"log/rift.err.log"
  end

  test do
    system bin/"rift-cli", "--help"
  end
end
