# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rift < Formula
  desc "Tiling window manager for macOS (nicks fork of acsandmann/rift)"
  homepage "https://github.com/nicks/rift"
  version "0.5.7-nicks.2"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/nicks/rift/releases/download/v0.5.7-nicks.2/rift_0.5.7-nicks.2_darwin_amd64.tar.gz"
    sha256 "1e554c76255366a54d6f05b50232372f037d108721dd11147c8318e8816f84f2"

    define_method(:install) do
      bin.install "rift"
      bin.install "rift-cli"
      pkgshare.install "rift.default.toml"

      # Ad-hoc sign: rift talks to private SkyLight APIs and macOS is unhappy
      # about an unsigned binary holding Accessibility permissions.
      system "codesign", "--force", "-s", "-", "#{bin}/rift"
      system "codesign", "--force", "-s", "-", "#{bin}/rift-cli"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/nicks/rift/releases/download/v0.5.7-nicks.2/rift_0.5.7-nicks.2_darwin_arm64.tar.gz"
    sha256 "5a94d943532af0ecc10dfd4f33bfaaf5ae43d2d498d050618a2b1e8b785a3b42"

    define_method(:install) do
      bin.install "rift"
      bin.install "rift-cli"
      pkgshare.install "rift.default.toml"

      # Ad-hoc sign: rift talks to private SkyLight APIs and macOS is unhappy
      # about an unsigned binary holding Accessibility permissions.
      system "codesign", "--force", "-s", "-", "#{bin}/rift"
      system "codesign", "--force", "-s", "-", "#{bin}/rift-cli"
    end
  end

  conflicts_with "acsandmann/tap/rift"

  def caveats
    <<~EOS
      rift requires Accessibility permissions to control windows.
      Grant them in System Settings > Privacy & Security > Accessibility.

      To install the example configuration:
        mkdir -p ~/.config/rift
        cp #{HOMEBREW_PREFIX}/share/rift/rift.default.toml ~/.config/rift/config.toml

      To run rift in the background:
        brew services start nicks/tap/rift
    EOS
  end

  service do
    run [opt_bin/"rift"]
    keep_alive true
    process_type :interactive
    environment_variables PATH: std_service_path_env, LANG: "en_US.UTF-8"
    log_path var/"log/rift.log"
    error_log_path var/"log/rift.err.log"
  end

  test do
    system bin/"rift-cli", "--help"
  end
end
